#!/bin/bash
### Initial config of iRedMail that is used
### for building the Docker image.
### Configuration will be changed (customized)
### when the container is created.

export VMAIL_USER_HOME_DIR='/var/vmail'
export STORAGE_BASE_DIR='/var/vmail'
export STORAGE_MAILBOX_DIR='/var/vmail/vmail1'
export SIEVE_DIR='/var/vmail/sieve'
export BACKUP_DIR='/var/vmail/backup'
export BACKUP_SCRIPT_OPENLDAP='/var/vmail/backup/backup_openldap.sh'
export BACKUP_SCRIPT_MYSQL='/var/vmail/backup/backup_mysql.sh'
export BACKUP_SCRIPT_PGSQL='/var/vmail/backup/backup_pgsql.sh'
export DEFAULT_WEB_SERVER='NGINX'
export BACKEND_ORIG='MYSQL'
export BACKEND='MYSQL'
export VMAIL_DB_BIND_PASSWD='kdZmcwLuRU2GmP4maHd0yeRPHbPnaU'
export VMAIL_DB_ADMIN_PASSWD='NdmgHXe5HIYLWBAHUF2NPg59inRFId'
export LDAP_BINDPW='SPTIojZT0WjcFJZPIaOSuChWdt79aI'
export LDAP_ADMIN_PW='aMQEKvwdE9yzLOdNxPkIOt3OxQGJbZ'
export MYSQL_ROOT_PASSWD='SPTIojZT0WjcFJZPIaOSuChWdt79aI'
export MYSQL_ROOT_USER='root'
export SQL_SERVER='127.0.0.1'
export SQL_SERVER_PORT='3306'
export FIRST_DOMAIN='example.org'
export DOMAIN_ADMIN_NAME='SPTIojZT0WjcFJZPIaOSuChWdt79aI'
export SITE_ADMIN_NAME='postmaster@example.org'
export DOMAIN_ADMIN_PASSWD_PLAIN='SPTIojZT0WjcFJZPIaOSuChWdt79aI'
export DOMAIN_ADMIN_PASSWD='SPTIojZT0WjcFJZPIaOSuChWdt79aI'
export SITE_ADMIN_PASSWD='SPTIojZT0WjcFJZPIaOSuChWdt79aI'
export FIRST_USER='postmaster'
export FIRST_USER_PASSWD='SPTIojZT0WjcFJZPIaOSuChWdt79aI'
export FIRST_USER_PASSWD_PLAIN='SPTIojZT0WjcFJZPIaOSuChWdt79aI'
export ENABLE_DKIM='YES'
export USE_IREDADMIN='YES'
export USE_RCM='YES'
export USE_SOGO='YES'
export USE_AWSTATS='YES'
export USE_FAIL2BAN='YES'
export AMAVISD_DB_PASSWD='Usa0LN24TgJRoEOPuSFw62zf1F7Pdr'
export CLUEBRINGER_DB_PASSWD='sjpzOFrtyodxpw6rzWHkdD4RAXgz1r'
export IREDADMIN_DB_PASSWD='VTb3jGD1T81WqdORkVoEqT5TxeOqjG'
export RCM_DB_PASSWD='3nBErCmkhmq8JPOmqxcYEKBosKzQFq'
export SOGO_DB_PASSWD='xbHN1oSFhmoVd1kmnjUgtVzYcmmtbp'
export SOGO_SIEVE_MASTER_PASSWD='W4B7A5OcKMWx34VpRJufl1xl4PlxjN'
